services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER}
        USER_UID: ${UID}
        USER_GID: ${GID}
    container_name: dmacario_dotfiles
    volumes:
      - ..:/workspaces/dotfiles:cached
    command: sleep infinity
