#!/usr/bin/env bash

echo "Running install script as user $(whoami)"

if [ -n "$DOTFILES_BRANCH" ]; then
    echo "Using branch $DOTFILES_BRANCH"
fi

git fetch --unshallow origin "$DOTFILES_BRANCH":"$DOTFILES_BRANCH"
git switch "$DOTFILES_BRANCH"

../setup.sh
