services:
  dev-environment:
    container_name: dev-environment
    image: dev-env:0.0.0
    build:
      context: .
      args:
        REPO_DOTFILES: "https://github.com/davmacario/dotfiles.git"
        ENTRYPOINT: "./setup.sh"
        CUSTOM_BRANCH: "main"
        NVIM_VERSION: "v0.11.0"
